# Welcome to Numpy tutorial

In [1]:
import numpy as np

In [2]:
myArr = np.array([3,45,8,23])

In [3]:
myArr

array([ 3, 45,  8, 23])

In [4]:
myArr.dtype

dtype('int32')

In [5]:
myArr = np.array([23,35,23,23,1],np.int64)

In [6]:
myArr

array([23, 35, 23, 23,  1], dtype=int64)

In [7]:
myArr[0]

23

In [8]:
myArr[1]

35

# To 2D array creation and execution

In [9]:
myArr = np.array([[23,1,67,34]],np.int64)

In [10]:
myArr[0]

array([23,  1, 67, 34], dtype=int64)

In [11]:
myArr[0][1]

1

In [12]:
myArr[0][2]

67

In [13]:
myArr[0, 1]

1

In [14]:
myArr.shape

(1, 4)

In [15]:
myArr.dtype

dtype('int64')

In [16]:
a1D = np.array([1, 2, 3, 4],np.int8)
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]])

In [17]:
a1D,a2D,a3D

(array([1, 2, 3, 4], dtype=int8),
 array([[1, 2],
        [3, 4]]),
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]]))

In [18]:
a1D.shape

(4,)

In [19]:
a2D.shape

(2, 2)

In [20]:
a3D.shape

(2, 2, 2)

# Array creation : conversion from other python structures

In [21]:
listArr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [22]:
listArr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
listArr.shape

(3, 3)

In [24]:
listArr.dtype

dtype('int32')

In [25]:
listArr.size

9

In [26]:
zeros = np.zeros((2,5))

In [27]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
print(zeros.shape, zeros.size, zeros.dtype)

(2, 5) 10 float64


In [29]:
rng = np.arange(15)

In [30]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
lspace = np.linspace(1,8,8)

In [32]:
lspace

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [33]:
lspace = np.linspace(1,50,10)

In [34]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [35]:
lspace = np.linspace(1,5,6)

In [36]:
lspace

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [37]:
lspace = np.linspace(1,10,4)

In [38]:
lspace

array([ 1.,  4.,  7., 10.])

In [39]:
emp = np.empty((4,6)) # empty 2D array with random value assigned

In [40]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.06810200e-306, 9.34601642e-307, 1.42413555e-306],
       [1.78019082e-306, 1.37959740e-306, 6.23057349e-307,
        1.02360935e-306, 1.69120416e-306, 1.78022342e-306],
       [6.23058028e-307, 1.06811422e-306, 1.39071445e-307,
        8.01097889e-307, 1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 1.33510679e-306, 2.22522597e-306,
        1.24611674e-306, 1.29061821e-306, 2.29178686e-312]])

In [41]:
emp_like = np.empty_like(lspace)

In [42]:
emp_like

array([ 1.,  4.,  7., 10.])

In [43]:
ide = np.identity(5)

In [44]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
ide.shape

(5, 5)

In [46]:
newArr = np.arange(99)

In [47]:
newArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [48]:
newArr.reshape(3,33)
# newArr change nahi hoga, jisme assign hoga wo change hoga

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [49]:
newArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [50]:
# newArr.reshape(3,31) this gives error kyuki 99 elements! = 3*31

In [51]:
newArr = newArr.reshape(9,11)

In [52]:
newArr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
       [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [53]:
newArr.shape

(9, 11)

In [54]:
newArr = newArr.reshape(-1)

In [55]:
newArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [56]:
newArr = newArr.reshape(9,11)

In [57]:
newArr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
       [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [58]:
newArr = newArr.ravel() # does the same as newArr.reshape(-1)

In [59]:
newArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [60]:
newArr.shape

(99,)

In [61]:
x = [[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [62]:
ar = np.array(x)

In [63]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [64]:
ar.shape

(3, 3)

In [65]:
ar.sum(axis=0)

array([12,  8,  9])

In [66]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [67]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [68]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [69]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [70]:
ar.ndim # number of dimensions in ar

2

In [71]:
ar.shape

(3, 3)

In [72]:
ar.size

9

In [73]:
ar.nbytes

36

In [74]:
one = np.array([34,21,257,98])

In [75]:
one.argmax()
# It gives the index where maximum element is present in numpy array

2

In [76]:
one[one.argmax()]

257

In [77]:
one.argmin()

1

In [78]:
one.argsort()
# y sorted order of array return karga index-wise,
# [34,21,257,98]
# it will sat index 1 is first, index 0 is second, index 2 is third and index 2 will be last

array([1, 0, 3, 2], dtype=int64)

In [79]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [80]:
ar.argmax()
# It converts the 2D in one 1D and then returns it's index

6

In [81]:
ar.argmin()
# It converts the 2D in one 1D and then returns it's index

8

In [82]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [83]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [84]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [85]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [86]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [87]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [88]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [89]:
ar.reshape(9)

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [90]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [91]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [92]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [93]:
# In list , last me add ho jata tha
[34, 56] + [3, 221]

[34, 56, 3, 221]

In [94]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [95]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [96]:
ar.max()

7

In [97]:
ar.min()

0

In [98]:
ar.sum()

29

In [99]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [100]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [101]:
type(np.where(ar>5))

tuple

In [102]:
np.count_nonzero(ar)

8

In [103]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [104]:
ar[0, 1] =0

In [105]:
np.nonzero(ar)

(array([0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 2, 0, 1, 2, 0, 1], dtype=int64))

In [106]:
import sys

In [107]:
py_arr = [0,55,34,2]

In [108]:
np_arr = np.array(py_arr)

In [109]:
sys.getsizeof(1) * len(py_arr)

112

In [110]:
np_arr.itemsize * np_arr.size

16

In [111]:
np_arr.tolist()

[0, 55, 34, 2]